from test.utils import UTILS_TEST_DATA_FOLDER

CURRENT_TEST_DATA_FOLDER = UTILS_TEST_DATA_FOLDER / 'python'

PYPI_UTILS_TEST_DATA_FOLDER = CURRENT_TEST_DATA_FOLDER / 'pypi_utils'
REQUIREMENTS_UTILS_TEST_DATA_FOLDER = CURRENT_TEST_DATA_FOLDER / 'requirements_utils'
