from test import TEST_DATA_FOLDER

CURRENT_TEST_DATA_FOLDER = TEST_DATA_FOLDER / 'plugin_runner'

CREATE_VENV_TEST_DATA_FOLDER = CURRENT_TEST_DATA_FOLDER / 'create_venv'
PYTHON_VERSION_TEST_DATA_FOLDER = CURRENT_TEST_DATA_FOLDER / 'python_version'
BATCH_PROCESSING_TEST_DATA_FOLDER = CURRENT_TEST_DATA_FOLDER / 'batch_processing'
