from test.plugin_runner import BATCH_PROCESSING_TEST_DATA_FOLDER

RUNNERS_TEST_DATA_FOLDER = BATCH_PROCESSING_TEST_DATA_FOLDER / 'runners'

COMMON_DATASET = BATCH_PROCESSING_TEST_DATA_FOLDER / 'common_dataset'
DUMMY_CONFIG = BATCH_PROCESSING_TEST_DATA_FOLDER / 'dummy_config.yaml'
